---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocketchat-data-claim
  labels:
    placement: rocketchat-placement-1
spec:
  # --- INICIO DEL CAMBIO ---
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  # --- FIN DEL CAMBIO ---
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

